### PR TITLE
test for x-dead-letter-exchange and x-dead-letter-routing-key errors

### PR DESCRIPTION
**Pull request by dwburke**
Hello,

Somewhere between 0.005 and 0.007 (we upgraded from 5->7), we have been unable to create queues with x-dead-letter-exchange and x-dead-letter-routing-key args... we get the error 

Declaring queue: server channel error 406, message: PRECONDITION_FAILED - invalid type 'binary' for arg 'x-dead-letter-exchange' in queue 'amq.gen-OTZiCGpYgi81jt4Y93sU7w' in vhost '/'

I verified it still exists in 0.010000 (latest on cpan).

I've been digging into some this evening, but I wanted to send you a commit with the test fail in case you had some insight to the problem, being more directly familiar with the module internals.

Thanks,
Dan.

### CODE REVIEW

**Comment by manchicken** [comment]
Hey @dwburke, I'm not quite sure what's going on with that... strings are transmitted as byte arrays in AMQP. I'm wondering, just for the sake of fun, could you try making sure that you set UTF-8 on that and see what happens? I'm not sure if that will fix this, but it could help troubleshoot itmore.

**Comment by alnewkirk** [comment]
I've experienced this problem as well, and for the time being, have switched to Net::RabbitMQ. Thankfully I'm using Beam::Wire for DI and the Net::RabbitMQ API is identical to the Net::AMQP::RabbitMQ API, so switch was literally a one-line configuration change. 

Having battled with this issue for a few hours, it seems to me that declaring a queue with the optional arguments hash containing `x-dead-letter-exchange` and/or `x-dead-letter-queue-routing-key` properties, results in an error:

```
Declaring queue: server channel error 406, message: PRECONDITION_FAILED - invalid type 'binary' for arg 'x-dead-letter-exchange' in queue '...'
```

My educated guess is that the C and/or XS code that handles the values within the optional arguments hash is not accounting for the dead-letting properties. FWIW, the `x-message-ttl` and `x-expires` properties work just fine.

**Comment by manchicken** [comment]
The properties should support infinite nesting now adays, it sounds like there's a weirdness in what is being sent for the type of that property.

I'll look into this in the next couple of weeks.

**Comment by manchicken** [comment]
I think that #41 is the issue which we can use to track this. I'll link to this pull request so we can see the original pull request with the test.

I **sincerely** appreciate you giving us a test, that made this so much easier to track down.

I'm closing this and we can track this on #41 now.

**Comment by dwburke** [comment]
Glad it helps.  Sorry I wasn't able to try the utf8 thing, been down for the count with the flu.  Let me know if there's anything I can do to help.

**Pull request closed without merging**
