### PR TITLE
Add function get_sockfd for retreiving socket

### PR DESCRIPTION
**Pull request by DavsX**
Based on: https://github.com/markwellis/net-amqp-rabbitmq/issues/49

### CODE REVIEW

**Comment by markwellis** [comment]
this looks ok to me, what do you think @manchicken?

@DavsX  is there any chance you'd be able to add a test or two?

**Comment by manchicken** [comment]
Sorry, I totally just saw this. I'm not sure why we would want this
function, it seems particularly dangerous to do anything with the return
value.

That said, I'm not opposed to it being there, I just don't know what use
people would have for it.

I also would have liked to seen some tests for this.

**Comment by markwellis** [comment]
same, but i figured it must have a use. i'll leave it undocumented, so if you find it and use it it's your own fault if it breaks!

**Comment by DavsX** [comment]
If I want to handle multiple sockets (IO) at once, I must poll/select on them - that is why I need the raw socket itself. Using some event-mechanism like AnyEvent proved poorly during our performance tests. Using the consume/recv trick described here https://github.com/markwellis/net-amqp-rabbitmq/issues/49 is not good for our use case, because I don't want to wait for some event to happen on the other sockets to receive AMQP data (the business logic is based on blocking the main process by IO::Poll and acting on it, when some data comes in). Basically now I poll on the raw socket and when there is any data, I use my Net::AMQP::RabbitMQ object to communicate.

Unfortunately as far a tests goes I cannot promise anything. Not sure what those tests should aim for.

**Comment by markwellis** [comment]
@DavsX re tests, no idea, that a socket is returned? i dunno, it's mainly to make sure that it keeps working when we add change features/upgrade librabbitmq. it doesn't really have to do much else, and if it's not possible it doesn't really matter, since it's a secret function

**Comment by manchicken** [comment]
@Dávid, AMQP is a multiplexing protocol, why do you want multiple sockets?
It sounds like you’re working against the protocol, what you’re doing seems
like what channels is designed for.

Also, if you want two connections, you can just have two instances of
Net::AMQP::RabbitMQ, no?
​

**Comment by DavsX** [comment]
Sorry, my description was not complete. I only have 1 connection to RabbitMQ, but I have several INET/UNIX etc sockets. For example I am pulling on a RabbitMQ and a Unix socket in one of my daemons, acting as a middleware (which message formatting etc). In that case AMQP is used as a gateway between different systems.

**Comment by manchicken** [comment]
Like a load balancer?

**Comment by DavsX** [comment]
Well it is a business task, so I must do it. Not like a load balancer. We are slowly migrating our system to a new codebase. This act like kinda a gateway for the two..Or maybe like a reverse-proxy. Hard to say, but I know for sure, that I need some polling mechanism on both AMQP and INET sockets :)

**Comment by manchicken** [comment]
That sounds awful, I'm sorry.

I'm not opposed to this pull request but we should have a test if you can
make one.

**Comment by DavsX** [comment]
We'll I am already trying to make it work, so far with good results. The get_sockfd function in this PR returns an integer, so I have to call IO::Handle->new_from_fd($sock_fd, "r+"); on it, before I can use it.

**Comment by manchicken** [comment]
I added some tests for this (very simple tests) in pull request #76.

**Pull request merged**
