### PR TITLE
Adding 64-bit delivery tags, updated tests.

### PR DESCRIPTION
**Pull request by manchicken**
This fixes some compile warnings, updated the code to make delivery tags use uint64_t and then updated tests to play nice with this change.

### CODE REVIEW

**Comment by manchicken** [comment]
## PLEASE HOLD ON MERGE

I've got this pull request going mostly to make sure that it builds and passes Travis in the upstream master. Please wait until I've had a chance to look at my Travis results before merging.

**Comment by manchicken** [comment]
@autarch, could you please review these changes?

@markwellis, could you also review these changes? I think they might be good for merging now (finally).

**Comment by markwellis** [comment]
@manchicken it looks good to me, but that doesn't mean a lot!

**Comment by manchicken** [comment]
Coming from you, it means a lot!

**Comment by autarch** [comment]
This looks good, but I really wish this distro had more and better tests. AFAICT, the tests don't cover many of these changes :(

**Comment by manchicken** [comment]
@autarch , I'll see what I can do about that.

**Pull request merged**
