### PR TITLE
closes #63 - clear memory pool when we can

### LINKED ISSUE #63: [Solution proposed] Growing memory usage after publish
Hi! I've found a nasty memory leak, which happens on publish, if in the last argument (props hash) we have headers defined.

A sample/simple script can be found below. The leaking can be stopped by commenting out the `headers => {}` hash. The leaking can be seen with for example `htop`. My attempts to find the cause of this were unsuccessful. Also turning on DEBUG in `RabbitMQ.xs` and publishing something with the `headers` hash set in the `props` hash results in segfault.

```perl
#!/usr/bin/env perl

use strict;
use warnings;

use Net::AMQP::RabbitMQ;

my $exchange = "test_queue";
my $queue = "test_queue";

my $mq = Net::AMQP::RabbitMQ->new();
$mq->connect("localhost", {
    user => 'guest',
    password => 'guest',
    port => '5672',
    vhost => '/',
}) or die "connect $!";

$mq->channel_open(1);
$mq->purge(1, $queue);

for (1..500000) {
    $mq->publish(1, "", "Test data", { exchange => $exchange }, {
        headers => {
			leakMe => "Hello World, I'm leaking!",
        },
    });
}

$mq->purge(1, $queue);
```

### PR DESCRIPTION
**Pull request by markwellis**
and clear the connection memory pool when it's safe, which is much nicer
than the horrible hack i did to fix the memory leak on transaction commit

### CODE REVIEW

**Comment by markwellis** [comment]
@manchicken  can you review this, see if it makes sense and isn't going to do crazy undefined things!

**Comment by manchicken** [comment]
Could we add a test which has an array inside of a table in the headers? Since we're merging the pools, I think we should make sure there isn't any bleed.

**Comment by markwellis** [comment]
@manchicken this should be a better check of the headers/arrays thing.

**Comment by manchicken** [comment]
Yes! Good stuff. Did we verify that this fixes the memory growth?

**Comment by markwellis** [comment]
Yes, I added a new test which confirms it, and it should fix it in the places where it was a problem but never noticed (anywhere that used hash_to_amqp_table or array_to_amqp_table!)

It's all my fault, because I allocated a pool of memory for doing things, and expanded it everytime I needed to do something new, but never reclaimed it. Memory management is hard, this is why I code in perl and not c!

i found that librabbitmq-c had a function to recycle the internal memory pool when it's safe to do so, which we weren't calling. so i call a wrapper that calls that after we've done something, and that wrapper will also recycle our pool as well.

I have made an assumption here that if it's safe to recycle the internal memory, then it's ok to recycle ours - I can't see a reason why it wouldn't be, and it's much better than the awful way I was dealing with the previous leak in commit (emptying the internal memory pool regardless of it being safe or not! :( )

**Pull request merged**
